// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ActionCommand {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ActionCommand {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

type():number {
  return this.bb!.readUint8(this.bb_pos);
}

power():number {
  return this.bb!.readUint8(this.bb_pos + 1);
}

duration():number {
  return this.bb!.readUint8(this.bb_pos + 2);
}

static sizeOf():number {
  return 3;
}

static createActionCommand(builder:flatbuffers.Builder, type: number, power: number, duration: number):flatbuffers.Offset {
  builder.prep(1, 3);
  builder.writeInt8(duration);
  builder.writeInt8(power);
  builder.writeInt8(type);
  return builder.offset();
}

}
